// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eShopGrpcService.Data;

#nullable disable

namespace eShopGrpcService.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eShopGrpcService.Models.CatalogBrand", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CatalogBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Azure"
                        },
                        new
                        {
                            Id = 2,
                            Brand = ".NET"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Visual Studio"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "SQL Server"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Other"
                        });
                });

            modelBuilder.Entity("eShopGrpcService.Models.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CatalogBrandId")
                        .HasColumnType("int");

                    b.Property<int>("CatalogTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picturefilename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(19, 4)
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("CatalogBrandId");

                    b.HasIndex("CatalogTypeId");

                    b.ToTable("CatalogItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatalogBrandId = 2,
                            CatalogTypeId = 2,
                            Description = ".NET Bot Black Hoodie",
                            Name = ".NET Bot Black Hoodie",
                            Picturefilename = "2.png",
                            Price = 19.5m
                        },
                        new
                        {
                            Id = 2,
                            CatalogBrandId = 2,
                            CatalogTypeId = 1,
                            Description = ".NET Black & White Mug",
                            Name = ".NET Black & White Mug",
                            Picturefilename = "11.png",
                            Price = 8.50m
                        },
                        new
                        {
                            Id = 3,
                            CatalogBrandId = 5,
                            CatalogTypeId = 2,
                            Description = "Prism White T-Shirt",
                            Name = "Prism White T-Shirt",
                            Picturefilename = "7.png",
                            Price = 12m
                        },
                        new
                        {
                            Id = 4,
                            CatalogBrandId = 2,
                            CatalogTypeId = 2,
                            Description = ".NET Foundation T-shirt",
                            Name = ".NET Foundation T-shirt",
                            Picturefilename = "5.png",
                            Price = 12m
                        },
                        new
                        {
                            Id = 5,
                            CatalogBrandId = 5,
                            CatalogTypeId = 3,
                            Description = "Roslyn Red Sheet",
                            Name = "Roslyn Red Sheet",
                            Picturefilename = "9.png",
                            Price = 8.5m
                        },
                        new
                        {
                            Id = 6,
                            CatalogBrandId = 2,
                            CatalogTypeId = 2,
                            Description = ".NET Blue Hoodie",
                            Name = ".NET Blue Hoodie",
                            Picturefilename = "1.png",
                            Price = 12m
                        },
                        new
                        {
                            Id = 7,
                            CatalogBrandId = 5,
                            CatalogTypeId = 2,
                            Description = "Roslyn Red T-Shirt",
                            Name = "Roslyn Red T-Shirt",
                            Picturefilename = "6.png",
                            Price = 12m
                        },
                        new
                        {
                            Id = 8,
                            CatalogBrandId = 5,
                            CatalogTypeId = 2,
                            Description = "Kudu Purple Hoodie",
                            Name = "Kudu Purple Hoodie",
                            Picturefilename = "3.png",
                            Price = 8.5m
                        },
                        new
                        {
                            Id = 9,
                            CatalogBrandId = 5,
                            CatalogTypeId = 1,
                            Description = "Cup<T> White Mug",
                            Name = "Cup<T> White Mug",
                            Picturefilename = "12.png",
                            Price = 12m
                        },
                        new
                        {
                            Id = 10,
                            CatalogBrandId = 2,
                            CatalogTypeId = 3,
                            Description = ".NET Foundation Sheet",
                            Name = ".NET Foundation Sheet",
                            Picturefilename = "8.png",
                            Price = 12m
                        },
                        new
                        {
                            Id = 11,
                            CatalogBrandId = 2,
                            CatalogTypeId = 3,
                            Description = "Cup<T> Sheet",
                            Name = "Cup<T> Sheet",
                            Picturefilename = "10.png",
                            Price = 8.5m
                        },
                        new
                        {
                            Id = 12,
                            CatalogBrandId = 5,
                            CatalogTypeId = 2,
                            Description = "Cup<T> TShirt",
                            Name = "Cup<T> TShirt",
                            Picturefilename = "4.png",
                            Price = 12m
                        });
                });

            modelBuilder.Entity("eShopGrpcService.Models.CatalogItemsStock", b =>
                {
                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("AvailableStock")
                        .HasColumnType("int");

                    b.Property<int>("CatalogItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.HasKey("StockId");

                    b.ToTable("CatalogItemsStock");

                    b.HasData(
                        new
                        {
                            StockId = 1,
                            AvailableStock = 100,
                            CatalogItemId = 1,
                            Date = new DateTime(2017, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StockId = 2,
                            AvailableStock = 120,
                            CatalogItemId = 1,
                            Date = new DateTime(2017, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StockId = 3,
                            AvailableStock = 80,
                            CatalogItemId = 1,
                            Date = new DateTime(2017, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StockId = 4,
                            AvailableStock = 45,
                            CatalogItemId = 2,
                            Date = new DateTime(2017, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StockId = 5,
                            AvailableStock = 65,
                            CatalogItemId = 4,
                            Date = new DateTime(2017, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StockId = 6,
                            AvailableStock = 22,
                            CatalogItemId = 5,
                            Date = new DateTime(2017, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("eShopGrpcService.Models.CatalogType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CatalogTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Mug"
                        },
                        new
                        {
                            Id = 2,
                            Type = "T-Shirt"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Sheet"
                        },
                        new
                        {
                            Id = 4,
                            Type = "USB Memory Stick"
                        });
                });

            modelBuilder.Entity("eShopGrpcService.Models.DiscountItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("End")
                        .HasColumnType("date");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<DateTime>("Start")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("DiscountItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = new DateTime(2017, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Size = 0.29999999999999999,
                            Start = new DateTime(2017, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            End = new DateTime(2017, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Size = 0.25,
                            Start = new DateTime(2017, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            End = new DateTime(2017, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Size = 0.10000000000000001,
                            Start = new DateTime(2017, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            End = new DateTime(2017, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Size = 0.5,
                            Start = new DateTime(2017, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            End = new DateTime(2017, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Size = 0.29999999999999999,
                            Start = new DateTime(2017, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            End = new DateTime(2017, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Size = 0.25,
                            Start = new DateTime(2017, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("eShopGrpcService.Models.CatalogItem", b =>
                {
                    b.HasOne("eShopGrpcService.Models.CatalogBrand", "CatalogBrand")
                        .WithMany()
                        .HasForeignKey("CatalogBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShopGrpcService.Models.CatalogType", "CatalogType")
                        .WithMany()
                        .HasForeignKey("CatalogTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogBrand");

                    b.Navigation("CatalogType");
                });
#pragma warning restore 612, 618
        }
    }
}
