apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eshop.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
data:
  UseMockData: {{ .Values.config.useMockData | quote }}
  UseCustomizationData: {{ .Values.config.useCustomizationData | quote }}
  UseAzureStorage: {{ .Values.config.useAzureStorage | quote }}
  UseAzureActiveDirectory: {{ .Values.config.useAzureActiveDirectory | quote }}
