spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=Microsoft.eShopOnContainers.Services.CatalogDb;encrypt=false
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

catalog:
  use-mock-data: false
  use-customization-data: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

server:
  port: 8080
