FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["eShopGrpcService/eShopGrpcService.csproj", "eShopGrpcService/"]
RUN dotnet restore "eShopGrpcService/eShopGrpcService.csproj"
COPY eShopGrpcService/ eShopGrpcService/
WORKDIR "/src/eShopGrpcService"
RUN dotnet build "eShopGrpcService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "eShopGrpcService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:5001
ENTRYPOINT ["dotnet", "eShopGrpcService.dll"]
